### ISSUE TITLE
[Request] Play from the last played song in a album

### ISSUE THREAD

**Issue by iiTzRichie** [Samych02/Resume-Playlist#1]
If it's possible, could the same functionality be applied to albums?

**Comment by Samych02** [comment]
Can you send me an album link for testing purposes?

**Comment by iiTzRichie** [comment]
> Can you send me an album link for testing purposes?

https://open.spotify.com/album/3MKvhQoFSrR2PrxXXBHe9B?si=7-ottDOeSxGfgtwo8FQS-Q

**Comment by Samych02** [comment]
The extension now supports albums as well, can you update the extension and check if it works as intended?

**Comment by iiTzRichie** [comment]
> The extension now supports albums as well, can you update the extension and check if it works as intended?

Can confirm it works! Awesome! Thank you!
