### ISSUE TITLE
Broken in Spotify 1.2.47.364?

### ISSUE THREAD

**Issue by lead0r** [Samych02/Resume-Playlist#3]
I'm on :

Spotify für macOS (Apple Silicon)
1.2.47.364.gf06e5cee
Spicetify v2.38.3

and have the plugin installed, but since the Spotify update, the option to resume playlist from last played song does not exist anymore

**Comment by Samych02** [comment]
I am also facing the same problem on the same platform with this and many other extensions, I will try to investigate the problem asap.

**Comment by Samych02** [comment]
The new spotify update (>1.2.47) broke context menus, which means that you have to downgrade it.
Check this post for old versions links: https://x.com/spicetifyapp/status/1838942526050369882
Edit: it has been fixed in the newest spicetfy update (v2.38.4), you just need to run `spicetify update`
